# Site settings
author: Jennifer Miller
title: 
header-img: img/home-bg.png
email: jmiller@archersystems.us
copyright_name: Jennifer Miller
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mumu2117

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
